
import {ObjectId} from 'mongodb';
import {createException as ex} from 'shared/exceptions';

/* @ToDo: maybe this shouldn't throw? but it should also not use promise... */
export function wrapAndCheckId(idString) {
  if(ObjectId.isValid(idString)) {
    return new ObjectId(idString);
  } else {
    throw ex('invalid_argument', 'Passed idString is not valid');
  }
}
